# Generated by Django 3.1.4 on 2021-01-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0003_reservacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='imagendestacada',
            field=models.ImageField(blank=True, null=True, upload_to='imageshostales'),
        ),
    ]
