# Generated by Django 3.1.4 on 2021-01-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0004_auto_20210128_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='Personas',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='pdf',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
