# Generated by Django 3.1.4 on 2021-01-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0008_auto_20210128_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='Observaciones',
            field=models.TextField(null=True),
        ),
    ]
