# Generated by Django 3.1.4 on 2021-01-29 07:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0009_reservacion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='Imagen_Pasaje',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='reservaciones/pasaje'),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='Imagen_Pasaporte',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='reservaciones/pasaportes'),
        ),
    ]
