# Generated by Django 3.1.4 on 2021-01-31 16:02

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0011_auto_20210129_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name': 'Reservación', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Pasaporte', models.CharField(max_length=7)),
                ('Email', models.EmailField(max_length=254)),
                ('Imagen_Pasaporte', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='reservaciones/pasaportes')),
                ('Imagen_Pasaje', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='reservaciones/pasaje')),
                ('Reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostal.reservacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
