# Generated by Django 3.1.4 on 2021-02-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0011_auto_20210129_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='Pasaporte',
            field=models.CharField(max_length=12),
        ),
    ]
