# Generated by Django 3.1.4 on 2021-05-04 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0013_auto_20210202_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostal',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Reservacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostal.reservacion'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='HoraEntrada',
            field=models.DateTimeField(verbose_name='Fecha y hora de entrada'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='HoraSalida',
            field=models.DateTimeField(verbose_name='Fecha y hora de entrada'),
        ),
    ]
