# Generated by Django 3.1.4 on 2021-01-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_userprofile_pasaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Telefono',
            field=models.CharField(default='00000000000', max_length=15),
        ),
    ]
