# Generated by Django 3.1.4 on 2021-01-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostal', '0006_remove_reservacion_imagendestacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='Reservado_Por',
            field=models.ForeignKey(default=object, on_delete=django.db.models.deletion.CASCADE, to='usuario.userprofile'),
            preserve_default=False,
        ),
    ]
