# Generated by Django 3.1.4 on 2021-01-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0009_reservacion_reservado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='Reservado_Por',
        ),
    ]
