# Generated by Django 3.1.4 on 2021-01-28 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostal', '0010_remove_reservacion_reservado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='Reservado_Por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
