# Generated by Django 3.1.4 on 2021-02-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0012_auto_20210131_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='Imagen_Pasaje',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='Imagen_Pasaporte',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='Pasaporte',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='aNombre',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='hostal.cliente', verbose_name='A nombre de'),
            preserve_default=False,
        ),
    ]
